### ISSUE TITLE
更加丝滑的切换进度条

### ISSUE THREAD

**Issue by liulyxandy-codemao** [zaona/UEFilesSite#1]
这是现在的切换进度条：

https://github.com/zaona/UEFilesSite/assets/65491750/59ff1aed-ec96-45cc-9ab9-78dc958788bc

这是GitHub的切换进度条：

https://github.com/zaona/UEFilesSite/assets/65491750/07ad8608-f27f-417c-be47-5f49da4b2e33

区别在于一个需要在加载链接页面后才开始运行，一个点击链接时就会开始运行。
希望可以让切换像GitHub一样丝滑（？

**Comment by zaona** [comment]
用原生应该是无法实现了
![image](https://github.com/zaona/UEFilesSite/assets/69132416/14bb0baf-5cd3-4f80-974d-a971268e681c)

**Comment by liulyxandy-codemao** [comment]
其实也不是不行，只是实现办法粗糙了一些
#2
